[project]
name = "timeseries-validator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Emilia Masiak", email = "90275335+Emka5885@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
